name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "export PATH=$HOME/.rustup/bin:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: Install nightly toolchain
        run: |
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --release
      - name: Run tests (optional)
        run: cargo test
